### ISSUE TITLE
Job runner quits after start 

### ISSUE THREAD

**Issue by exu** [bamzi/jobrunner#2]
I'm trying to run jobrunner but it quits right after start: 
```
package main

import (
	"fmt"
	"github.com/bamzi/jobrunner"
)

func main() {
	jobrunner.Start(10, 1)
	jobrunner.Schedule("@every 5s", ReminderEmails{})
}

type ReminderEmails struct {
}

func (e ReminderEmails) Run() {
	fmt.Printf("Every 5 sec send reminder emails \n")
}
```
Output: 

```
❯ go run app.go
[JobRunner] 2015/10/30 - 09:48:06 Started...  
                                                                                                  
❯ 

```

Go version
```
go version go1.5.1 linux/amd64
```

**Comment by alehano** [comment]
Your program exited. Try to add for {} at the end of main.

**Comment by exu** [comment]
ok working thanks :)

**Comment by bamzi** [comment]
@alehano Thank you for helping

@exu If you don't intend to use a http server session then you need to keep the app running with `{}` or `select {}` at the end of the `func main() {...}`. 

However, the problem is, if any crash happens mid process (i.e. at 3am) then everything is stopped and you cannot recover unless you manually restart the app.
